[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "zlib", "libjpeg", "libpng", "freetype", "gcc"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install Pillow==10.3.0",
  "pip install pyTelegramBotAPI==4.21.0",
  "pip install requests==2.31.0"
]

[start]
cmd = "python bot.py"
