
[phases.setup]
nixPkgs = ["python3", "zlib", "libjpeg", "libpng", "freetype"]

[phases.install]
cmds = [
  "pip install --break-system-packages Pillow==10.3.0",
  "pip install --break-system-packages pyTelegramBotAPI==4.21.0",
  "pip install --break-system-packages requests==2.31.0"
]

[start]
cmd = "python bot.py"
